### ISSUE TITLE
Define project scope and goals

### ISSUE THREAD

**Issue by kuon** [ino1sr/kana-cards#1]
- What problem the project solves and how, general description
- Targeted users and platform
- Technical requirements and scope (backend needed? what programming language? ...)
- Assets requirement (images, sounds, ...)
- Localization requirement

**Comment by ino1sr** [comment]
>     * What problem the project solves and how, general description

The project helps kids to learn japanese characters (hiragana and katakana). It is a kana flash card
on the mobile.

>     * Targeted users and platform

My kids. Platform is mobile smartphone/tablet.
 
>     * Technical requirements and scope (backend needed? what programming language? ...)
 
Frontend in elm, no backend required. Should run on my phone.

>     * Assets requirement (images, sounds, ...)

First version will be without image (unicode char used), no sound.

>     * Localization requirement

Only in japanese, no i18n needed.
